# --- !Ups

CREATE TABLE PASSWORD_INFO (
    id BIGINT NOT NULL PRIMARY KEY,
    login_info_id BIGINT NOT NULL,
    hasher VARCHAR(1024) NOT NULL,
    password VARCHAR(1024) NOT NULL,
    salt VARCHAR(1024),
    CONSTRAINT FK_PI_LOGIN_INFO_ID FOREIGN KEY (login_info_id) REFERENCES LOGIN_INFO (id) ON DELETE CASCADE,
    CONSTRAINT UQ_PI_LOGIN_INGO_ID UNIQUE (login_info_id)
);

CREATE TABLE REGISTRATION_TOKENS (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    hasher VARCHAR(1024) NOT NULL,
    password VARCHAR(1024) NOT NULL,
    salt VARCHAR(1024),
    created_at DATETIME NOT NULL,
    expires_at DATETIME NOT NULL,
    INDEX IX_RT_EXPIRES_AT (expires_at)
);

# --- !Downs

DROP TABLE PASSWORD_INFO;
DROP TABLE REGISTRATION_TOKENS;
