version: '3'
services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  ldap:
    build:
      context: ./openldap
    volumes:
      - ./openldap/ldif:/ldif

  lam:
    build:
      context: ./ldap-account-manager
