version: '3'
services:
  haproxy:
    build:
      context: ./haproxy

  client:
    build:
      context: ./client
    entrypoint: tail
    command:
      - "-f"
      - "/dev/null"

  server:
    build:
      context: ./server
    cap_add:
      - NET_ADMIN
