#
# Cookbook:: zabbix-agent
# Recipe:: default
#
# Copyright:: 2017, The Authors, All Rights Reserved.

#
# This cookbook was tested only for Amazon Linux AMI release 2017.03
#

# Register a repository of zabbix 3.2
# `not_if` executes a given string as shell command (or code block as ruby script).
# `not_if` prevents a resource from executing when the condition is true.
# https://docs.chef.io/resource_common.html#guards
remote_file '/tmp/zabbix-release-3.2-1.el6.noarch.rpm' do
    source "http://repo.zabbix.com/zabbix/3.2/rhel/6/x86_64/zabbix-release-3.2-1.el6.noarch.rpm"
    not_if 'rpm -qa | grep -q "zabbix-release-3.2-1.el6.noarch"'
    action :create
    notifies :install, "rpm_package[zabbix]", :immediately
end

rpm_package "zabbix" do
    source '/tmp/zabbix-release-3.2-1.el6.noarch.rpm'
    action :install
end

# Install zabbix-agent
# https://docs.chef.io/resource_package.html
package 'zabbix-agent' do
    action :install
end

# Prepare a configuration file for zabbix-agent.
# The configuration file is generated by the below resources.
#   - template file (`templates/zabbix_agentd.conf.erb`)
#   - attirbute file (`attributes/agent.rb`)
# https://docs.chef.io/resource_template.html
template '/etc/zabbix/zabbix_agentd.conf' do
    source 'zabbix_agentd.conf.erb'
    owner'root'
    group 'root'
    mode '0644'
    action :create
end

# Start and enable zabbix-agent
# service 'zabbix-agent' do
#     action [:enable, :start]
# end
